# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rdm_gui_stackedpages.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 505)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QWidget {\n"
"    color: rgb(218, 218, 218);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QStackedWidget{\n"
"    background-color: red;\n"
"    color: rgb(218, 218, 218);\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(118, 118, 113);\n"
"    height: 40px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: transparent;\n"
"    color: rgb(100, 95, 95);\n"
"}\n"
"\n"
"QPushButton {\n"
"               background-color: rgb(59, 56, 56, 80);\n"
"               height: 40px;\n"
"               padding: 0px 5px 0px 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"               background-color: transparent;\n"
"               border: 1px solid gray;\n"
"               border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"               border: 1px solid gray;\n"
"               border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"               background-color: gray;\n"
"               color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"               border: 1px solid white;\n"
"               border-radius: 5px;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0px 10px 0px 10px;\n"
"    left: 10px;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background: black;\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane {\n"
"    background-color: transparent;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: left;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: rgb(59, 56, 56);\n"
"    border: 1px solid gray;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 rgb(59, 56, 56), stop: 0.4 rgb(100, 95, 95),\n"
"                                stop: 0.5 rgb(80, 75, 75), stop: 1.0 rgb(59, 56, 56));\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QStackedWidget {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QRadioButton {\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 30px;\n"
"    height: 30px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: rgb(59, 56, 56);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgb(59, 56, 56);\n"
"    selection-background-color: lightgray;\n"
"\n"
"}\n"
"\n"
"QProgressBar{\n"
"    background-color: rgb(59, 56, 56);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLCDNumber {\n"
"    border:1px solid gray;\n"
"    border-radius: 5px;\n"
"}\n"
"QSpinBox {\n"
"    color: rgb(218, 218, 218);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"   color: black\n"
"}\n"
"QRadioButton::indicator {\n"
"width: 32px;\n"
"height: 32px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked, QRadioButton::indicator:unchecked:pressed {\n"
"image: url(:/checkbox/graphics/checkbox_unchecked.png);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked, QRadioButton::indicator:checked:pressed, QRadioButton::indicator:checked:hover {\n"
"image: url(:/checkbox/graphics/checkbox_checked.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:hover {\n"
"image: url(:/checkbox/graphics/checkbox_hover.png);\n"
"}\n"
"\n"
"QLabel#label_5{\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"QLineEdit#veh_num_label{\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"    alignment: AlignHCenter;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 801, 481))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.Operator_page = QtWidgets.QStackedWidget(self.page)
        self.Operator_page.setEnabled(True)
        self.Operator_page.setGeometry(QtCore.QRect(0, 0, 801, 481))
        self.Operator_page.setObjectName("Operator_page")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Operator_page.addWidget(self.page_2)
        self.RDM_page_2 = QtWidgets.QWidget()
        self.RDM_page_2.setObjectName("RDM_page_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.RDM_page_2)
        self.groupBox_6.setGeometry(QtCore.QRect(37, 250, 351, 81))
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 25, 331, 46))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.veh_num_label_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.veh_num_label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.veh_num_label_2.setMaximumSize(QtCore.QSize(80, 45))
        self.veh_num_label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.veh_num_label_2.setText("")
        self.veh_num_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.veh_num_label_2.setObjectName("veh_num_label_2")
        self.horizontalLayout_8.addWidget(self.veh_num_label_2)
        self.veh_num_down_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.veh_num_down_2.setMinimumSize(QtCore.QSize(45, 0))
        self.veh_num_down_2.setMaximumSize(QtCore.QSize(70, 45))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.veh_num_down_2.setFont(font)
        self.veh_num_down_2.setDefault(False)
        self.veh_num_down_2.setFlat(False)
        self.veh_num_down_2.setObjectName("veh_num_down_2")
        self.horizontalLayout_8.addWidget(self.veh_num_down_2)
        self.veh_num_up_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.veh_num_up_2.setMinimumSize(QtCore.QSize(45, 0))
        self.veh_num_up_2.setMaximumSize(QtCore.QSize(70, 45))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.veh_num_up_2.setFont(font)
        self.veh_num_up_2.setDefault(False)
        self.veh_num_up_2.setFlat(False)
        self.veh_num_up_2.setObjectName("veh_num_up_2")
        self.horizontalLayout_8.addWidget(self.veh_num_up_2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.veh_num_save_btn_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.veh_num_save_btn_2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.veh_num_save_btn_2.setFont(font)
        self.veh_num_save_btn_2.setDefault(False)
        self.veh_num_save_btn_2.setFlat(False)
        self.veh_num_save_btn_2.setObjectName("veh_num_save_btn_2")
        self.horizontalLayout_7.addWidget(self.veh_num_save_btn_2)
        self.menuBtn_2 = QtWidgets.QPushButton(self.RDM_page_2)
        self.menuBtn_2.setGeometry(QtCore.QRect(20, 6, 40, 40))
        self.menuBtn_2.setMouseTracking(False)
        self.menuBtn_2.setStyleSheet("QPushButton {\n"
"    border-image: url(:/menu_graphics/graphics/menu_normal.png);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/menu_graphics/graphics/menu_pressed.png);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}")
        self.menuBtn_2.setText("")
        self.menuBtn_2.setIconSize(QtCore.QSize(50, 50))
        self.menuBtn_2.setCheckable(False)
        self.menuBtn_2.setDefault(True)
        self.menuBtn_2.setFlat(True)
        self.menuBtn_2.setObjectName("menuBtn_2")
        self.label_7 = QtWidgets.QLabel(self.RDM_page_2)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 800, 81))
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.RDM_page_2)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 800, 70))
        self.label_10.setObjectName("label_10")
        self.bgLabel_3 = QtWidgets.QLabel(self.RDM_page_2)
        self.bgLabel_3.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.bgLabel_3.setMouseTracking(True)
        self.bgLabel_3.setObjectName("bgLabel_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.RDM_page_2)
        self.groupBox_7.setGeometry(QtCore.QRect(410, 160, 361, 301))
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 32, 321, 241))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tm1Label_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.tm1Label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tm1Label_2.setObjectName("tm1Label_2")
        self.gridLayout_2.addWidget(self.tm1Label_2, 0, 0, 1, 1)
        self.tm1StatusBox_2 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.tm1StatusBox_2.setMouseTracking(False)
        self.tm1StatusBox_2.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.tm1StatusBox_2.setText("")
        self.tm1StatusBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.tm1StatusBox_2.setReadOnly(True)
        self.tm1StatusBox_2.setObjectName("tm1StatusBox_2")
        self.gridLayout_2.addWidget(self.tm1StatusBox_2, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.tm1_temp_LCD_2 = QtWidgets.QLCDNumber(self.layoutWidget_3)
        self.tm1_temp_LCD_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.tm1_temp_LCD_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tm1_temp_LCD_2.setLineWidth(1)
        self.tm1_temp_LCD_2.setSmallDecimalPoint(False)
        self.tm1_temp_LCD_2.setDigitCount(15)
        self.tm1_temp_LCD_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tm1_temp_LCD_2.setObjectName("tm1_temp_LCD_2")
        self.gridLayout_2.addWidget(self.tm1_temp_LCD_2, 1, 1, 1, 1)
        self.tm2Label_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.tm2Label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tm2Label_2.setObjectName("tm2Label_2")
        self.gridLayout_2.addWidget(self.tm2Label_2, 2, 0, 1, 1)
        self.tm2StatusBox_2 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.tm2StatusBox_2.setMouseTracking(False)
        self.tm2StatusBox_2.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.tm2StatusBox_2.setText("")
        self.tm2StatusBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.tm2StatusBox_2.setReadOnly(True)
        self.tm2StatusBox_2.setObjectName("tm2StatusBox_2")
        self.gridLayout_2.addWidget(self.tm2StatusBox_2, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1)
        self.tm2_temp_LCD_2 = QtWidgets.QLCDNumber(self.layoutWidget_3)
        self.tm2_temp_LCD_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.tm2_temp_LCD_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tm2_temp_LCD_2.setLineWidth(1)
        self.tm2_temp_LCD_2.setDigitCount(15)
        self.tm2_temp_LCD_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tm2_temp_LCD_2.setObjectName("tm2_temp_LCD_2")
        self.gridLayout_2.addWidget(self.tm2_temp_LCD_2, 3, 1, 1, 1)
        self.epbBtn_2 = QtWidgets.QPushButton(self.RDM_page_2)
        self.epbBtn_2.setGeometry(QtCore.QRect(740, 6, 40, 40))
        self.epbBtn_2.setStyleSheet("QPushButton {\n"
"    border-image: url(:/epb_graphics/graphics/epb_normal.png);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/epb_graphics/graphics/epb_pressed.png);\n"
"}")
        self.epbBtn_2.setText("")
        self.epbBtn_2.setIconSize(QtCore.QSize(50, 50))
        self.epbBtn_2.setFlat(True)
        self.epbBtn_2.setObjectName("epbBtn_2")
        self.inverterGroupdBox_2 = QtWidgets.QGroupBox(self.RDM_page_2)
        self.inverterGroupdBox_2.setGeometry(QtCore.QRect(37, 170, 351, 71))
        self.inverterGroupdBox_2.setObjectName("inverterGroupdBox_2")
        self.layoutWidget_4 = QtWidgets.QWidget(self.inverterGroupdBox_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(11, 25, 331, 34))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.TM1_radio_btn_2 = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.TM1_radio_btn_2.setEnabled(False)
        self.TM1_radio_btn_2.setObjectName("TM1_radio_btn_2")
        self.horizontalLayout_9.addWidget(self.TM1_radio_btn_2)
        self.TM2_radio_btn_2 = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.TM2_radio_btn_2.setEnabled(False)
        self.TM2_radio_btn_2.setObjectName("TM2_radio_btn_2")
        self.horizontalLayout_9.addWidget(self.TM2_radio_btn_2)
        self.Both_radio_btn_2 = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.Both_radio_btn_2.setEnabled(True)
        self.Both_radio_btn_2.setObjectName("Both_radio_btn_2")
        self.horizontalLayout_9.addWidget(self.Both_radio_btn_2)
        self.TorqueGroupdBox_2 = QtWidgets.QGroupBox(self.RDM_page_2)
        self.TorqueGroupdBox_2.setGeometry(QtCore.QRect(37, 340, 351, 81))
        self.TorqueGroupdBox_2.setObjectName("TorqueGroupdBox_2")
        self.layoutWidget_5 = QtWidgets.QWidget(self.TorqueGroupdBox_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(15, 23, 321, 47))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.torqueCmdMinus_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.torqueCmdMinus_2.setMinimumSize(QtCore.QSize(50, 45))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.torqueCmdMinus_2.setFont(font)
        self.torqueCmdMinus_2.setStyleSheet("QPushButton {\n"
"    font: 30pt \"MS Shell Dlg 2\";\n"
"}\n"
"")
        self.torqueCmdMinus_2.setObjectName("torqueCmdMinus_2")
        self.horizontalLayout_10.addWidget(self.torqueCmdMinus_2)
        self.torqueCmdBox_2 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.torqueCmdBox_2.setMinimumSize(QtCore.QSize(45, 45))
        self.torqueCmdBox_2.setText("")
        self.torqueCmdBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.torqueCmdBox_2.setObjectName("torqueCmdBox_2")
        self.horizontalLayout_10.addWidget(self.torqueCmdBox_2)
        self.torqueCmdPlus_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.torqueCmdPlus_2.setMinimumSize(QtCore.QSize(50, 45))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.torqueCmdPlus_2.setFont(font)
        self.torqueCmdPlus_2.setStyleSheet("QPushButton {\n"
"    font: 30pt \"MS Shell Dlg 2\";\n"
"}\n"
"")
        self.torqueCmdPlus_2.setFlat(False)
        self.torqueCmdPlus_2.setObjectName("torqueCmdPlus_2")
        self.horizontalLayout_10.addWidget(self.torqueCmdPlus_2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.RDM_page_2)
        self.groupBox_8.setGeometry(QtCore.QRect(37, 69, 351, 91))
        self.groupBox_8.setObjectName("groupBox_8")
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget_6.setGeometry(QtCore.QRect(11, 30, 331, 44))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.startStopBtn_2 = QtWidgets.QPushButton(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startStopBtn_2.setFont(font)
        self.startStopBtn_2.setStyleSheet("")
        self.startStopBtn_2.setObjectName("startStopBtn_2")
        self.horizontalLayout_11.addWidget(self.startStopBtn_2)
        self.enableBtn_2 = QtWidgets.QPushButton(self.layoutWidget_6)
        self.enableBtn_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enableBtn_2.setFont(font)
        self.enableBtn_2.setStyleSheet("")
        self.enableBtn_2.setObjectName("enableBtn_2")
        self.horizontalLayout_11.addWidget(self.enableBtn_2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.RDM_page_2)
        self.groupBox_9.setGeometry(QtCore.QRect(410, 70, 361, 80))
        self.groupBox_9.setObjectName("groupBox_9")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_7.setGeometry(QtCore.QRect(13, 30, 231, 37))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget_7)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_12.addWidget(self.radioButton_2)
        self.LED_2 = QtWidgets.QLabel(self.layoutWidget_7)
        self.LED_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LED_2.setStyleSheet("QLabel#LED_1 {\n"
"    image: url(:/LED/LED_1_M.png);\n"
"}\n"
"")
        self.LED_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LED_2.setObjectName("LED_2")
        self.horizontalLayout_12.addWidget(self.LED_2)
        self.Operator_page.addWidget(self.RDM_page_2)
        self.EPB_page_2 = QtWidgets.QWidget()
        self.EPB_page_2.setObjectName("EPB_page_2")
        self.bgLabel_4 = QtWidgets.QLabel(self.EPB_page_2)
        self.bgLabel_4.setGeometry(QtCore.QRect(-6, 0, 800, 480))
        self.bgLabel_4.setMouseTracking(True)
        self.bgLabel_4.setObjectName("bgLabel_4")
        self.label_13 = QtWidgets.QLabel(self.EPB_page_2)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 800, 70))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.EPB_page_2)
        self.label_14.setGeometry(QtCore.QRect(0, 0, 800, 81))
        self.label_14.setObjectName("label_14")
        self.groupBox_10 = QtWidgets.QGroupBox(self.EPB_page_2)
        self.groupBox_10.setGeometry(QtCore.QRect(34, 70, 321, 80))
        self.groupBox_10.setObjectName("groupBox_10")
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget_8.setGeometry(QtCore.QRect(13, 30, 291, 37))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget_8)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_13.addWidget(self.radioButton_3)
        self.LED_3 = QtWidgets.QLabel(self.layoutWidget_8)
        self.LED_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LED_3.setStyleSheet("QLabel#LED_1 {\n"
"    image: url(:/LED/LED_1_M.png);\n"
"}\n"
"")
        self.LED_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LED_3.setObjectName("LED_3")
        self.horizontalLayout_13.addWidget(self.LED_3)
        self.layoutWidget_8.raise_()
        self.label_13.raise_()
        self.label_13.raise_()
        self.groupBox_11 = QtWidgets.QGroupBox(self.EPB_page_2)
        self.groupBox_11.setGeometry(QtCore.QRect(34, 150, 321, 81))
        self.groupBox_11.setObjectName("groupBox_11")
        self.layoutWidget_9 = QtWidgets.QWidget(self.groupBox_11)
        self.layoutWidget_9.setGeometry(QtCore.QRect(10, 25, 301, 46))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_15.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.veh_num_label_3 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.veh_num_label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.veh_num_label_3.setMaximumSize(QtCore.QSize(80, 45))
        self.veh_num_label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.veh_num_label_3.setText("")
        self.veh_num_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.veh_num_label_3.setObjectName("veh_num_label_3")
        self.horizontalLayout_15.addWidget(self.veh_num_label_3)
        self.op_veh_num_down = QtWidgets.QPushButton(self.layoutWidget_9)
        self.op_veh_num_down.setMinimumSize(QtCore.QSize(45, 0))
        self.op_veh_num_down.setMaximumSize(QtCore.QSize(70, 45))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.op_veh_num_down.setFont(font)
        self.op_veh_num_down.setDefault(False)
        self.op_veh_num_down.setFlat(False)
        self.op_veh_num_down.setObjectName("op_veh_num_down")
        self.horizontalLayout_15.addWidget(self.op_veh_num_down)
        self.op_veh_num_up = QtWidgets.QPushButton(self.layoutWidget_9)
        self.op_veh_num_up.setMinimumSize(QtCore.QSize(45, 0))
        self.op_veh_num_up.setMaximumSize(QtCore.QSize(70, 45))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.op_veh_num_up.setFont(font)
        self.op_veh_num_up.setDefault(False)
        self.op_veh_num_up.setFlat(False)
        self.op_veh_num_up.setObjectName("op_veh_num_up")
        self.horizontalLayout_15.addWidget(self.op_veh_num_up)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_15)
        self.op_veh_num_save_btn = QtWidgets.QPushButton(self.layoutWidget_9)
        self.op_veh_num_save_btn.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.op_veh_num_save_btn.setFont(font)
        self.op_veh_num_save_btn.setDefault(False)
        self.op_veh_num_save_btn.setFlat(False)
        self.op_veh_num_save_btn.setObjectName("op_veh_num_save_btn")
        self.horizontalLayout_14.addWidget(self.op_veh_num_save_btn)
        self.groupBox_12 = QtWidgets.QGroupBox(self.EPB_page_2)
        self.groupBox_12.setGeometry(QtCore.QRect(380, 70, 401, 391))
        self.groupBox_12.setObjectName("groupBox_12")
        self.widget = QtWidgets.QWidget(self.groupBox_12)
        self.widget.setGeometry(QtCore.QRect(10, 30, 381, 341))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tm1Label_3 = QtWidgets.QLabel(self.widget)
        self.tm1Label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.tm1Label_3.setObjectName("tm1Label_3")
        self.gridLayout_4.addWidget(self.tm1Label_3, 0, 0, 1, 1)
        self.op_tm1StatusBox = QtWidgets.QLineEdit(self.widget)
        self.op_tm1StatusBox.setMouseTracking(False)
        self.op_tm1StatusBox.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.op_tm1StatusBox.setText("")
        self.op_tm1StatusBox.setAlignment(QtCore.Qt.AlignCenter)
        self.op_tm1StatusBox.setReadOnly(True)
        self.op_tm1StatusBox.setObjectName("op_tm1StatusBox")
        self.gridLayout_4.addWidget(self.op_tm1StatusBox, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.op_tm1_inv_temp_LCD = QtWidgets.QLCDNumber(self.widget)
        self.op_tm1_inv_temp_LCD.setMaximumSize(QtCore.QSize(16777215, 40))
        self.op_tm1_inv_temp_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.op_tm1_inv_temp_LCD.setLineWidth(1)
        self.op_tm1_inv_temp_LCD.setSmallDecimalPoint(False)
        self.op_tm1_inv_temp_LCD.setDigitCount(15)
        self.op_tm1_inv_temp_LCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.op_tm1_inv_temp_LCD.setObjectName("op_tm1_inv_temp_LCD")
        self.gridLayout_4.addWidget(self.op_tm1_inv_temp_LCD, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 2, 0, 1, 1)
        self.tm1_motor_temp_LCD = QtWidgets.QLCDNumber(self.widget)
        self.tm1_motor_temp_LCD.setMaximumSize(QtCore.QSize(16777215, 40))
        self.tm1_motor_temp_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tm1_motor_temp_LCD.setLineWidth(1)
        self.tm1_motor_temp_LCD.setSmallDecimalPoint(False)
        self.tm1_motor_temp_LCD.setDigitCount(15)
        self.tm1_motor_temp_LCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tm1_motor_temp_LCD.setObjectName("tm1_motor_temp_LCD")
        self.gridLayout_4.addWidget(self.tm1_motor_temp_LCD, 2, 1, 1, 1)
        self.tm2Label_3 = QtWidgets.QLabel(self.widget)
        self.tm2Label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.tm2Label_3.setObjectName("tm2Label_3")
        self.gridLayout_4.addWidget(self.tm2Label_3, 3, 0, 1, 1)
        self.tm2StatusBox_3 = QtWidgets.QLineEdit(self.widget)
        self.tm2StatusBox_3.setMouseTracking(False)
        self.tm2StatusBox_3.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.tm2StatusBox_3.setText("")
        self.tm2StatusBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.tm2StatusBox_3.setReadOnly(True)
        self.tm2StatusBox_3.setObjectName("tm2StatusBox_3")
        self.gridLayout_4.addWidget(self.tm2StatusBox_3, 3, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 4, 0, 1, 1)
        self.tm2_inv_temp_LCD_3 = QtWidgets.QLCDNumber(self.widget)
        self.tm2_inv_temp_LCD_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.tm2_inv_temp_LCD_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tm2_inv_temp_LCD_3.setLineWidth(1)
        self.tm2_inv_temp_LCD_3.setDigitCount(15)
        self.tm2_inv_temp_LCD_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tm2_inv_temp_LCD_3.setObjectName("tm2_inv_temp_LCD_3")
        self.gridLayout_4.addWidget(self.tm2_inv_temp_LCD_3, 4, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 5, 0, 1, 1)
        self.tm2_motor_temp_LCD = QtWidgets.QLCDNumber(self.widget)
        self.tm2_motor_temp_LCD.setMaximumSize(QtCore.QSize(16777215, 40))
        self.tm2_motor_temp_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tm2_motor_temp_LCD.setLineWidth(1)
        self.tm2_motor_temp_LCD.setDigitCount(15)
        self.tm2_motor_temp_LCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tm2_motor_temp_LCD.setObjectName("tm2_motor_temp_LCD")
        self.gridLayout_4.addWidget(self.tm2_motor_temp_LCD, 5, 1, 1, 1)
        self.label_14.raise_()
        self.label_13.raise_()
        self.label_18.raise_()
        self.tm1_motor_temp_LCD.raise_()
        self.label_19.raise_()
        self.tm2_motor_temp_LCD.raise_()
        self.epbBtn_3 = QtWidgets.QPushButton(self.EPB_page_2)
        self.epbBtn_3.setGeometry(QtCore.QRect(740, 6, 40, 40))
        self.epbBtn_3.setStyleSheet("QPushButton {\n"
"    border-image: url(:/epb_graphics/graphics/epb_normal.png);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/epb_graphics/graphics/epb_pressed.png);\n"
"}")
        self.epbBtn_3.setText("")
        self.epbBtn_3.setIconSize(QtCore.QSize(50, 50))
        self.epbBtn_3.setFlat(True)
        self.epbBtn_3.setObjectName("epbBtn_3")
        self.op_startStopBtn = QtWidgets.QPushButton(self.EPB_page_2)
        self.op_startStopBtn.setGeometry(QtCore.QRect(34, 260, 321, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.op_startStopBtn.setFont(font)
        self.op_startStopBtn.setStyleSheet("")
        self.op_startStopBtn.setObjectName("op_startStopBtn")
        self.bgLabel_4.raise_()
        self.label_14.raise_()
        self.label_13.raise_()
        self.groupBox_10.raise_()
        self.groupBox_11.raise_()
        self.groupBox_12.raise_()
        self.epbBtn_3.raise_()
        self.op_startStopBtn.raise_()
        self.Operator_page.addWidget(self.EPB_page_2)
        self.stackedWidget.addWidget(self.page)
        self.RDM_page = QtWidgets.QWidget()
        self.RDM_page.setObjectName("RDM_page")
        self.groupBox_3 = QtWidgets.QGroupBox(self.RDM_page)
        self.groupBox_3.setGeometry(QtCore.QRect(37, 250, 351, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.widget1 = QtWidgets.QWidget(self.groupBox_3)
        self.widget1.setGeometry(QtCore.QRect(10, 25, 331, 46))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.veh_num_label = QtWidgets.QLineEdit(self.widget1)
        self.veh_num_label.setMinimumSize(QtCore.QSize(0, 0))
        self.veh_num_label.setMaximumSize(QtCore.QSize(80, 45))
        self.veh_num_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.veh_num_label.setText("")
        self.veh_num_label.setAlignment(QtCore.Qt.AlignCenter)
        self.veh_num_label.setObjectName("veh_num_label")
        self.horizontalLayout.addWidget(self.veh_num_label)
        self.veh_num_down = QtWidgets.QPushButton(self.widget1)
        self.veh_num_down.setMinimumSize(QtCore.QSize(45, 0))
        self.veh_num_down.setMaximumSize(QtCore.QSize(70, 45))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.veh_num_down.setFont(font)
        self.veh_num_down.setDefault(False)
        self.veh_num_down.setFlat(False)
        self.veh_num_down.setObjectName("veh_num_down")
        self.horizontalLayout.addWidget(self.veh_num_down)
        self.veh_num_up = QtWidgets.QPushButton(self.widget1)
        self.veh_num_up.setMinimumSize(QtCore.QSize(45, 0))
        self.veh_num_up.setMaximumSize(QtCore.QSize(70, 45))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.veh_num_up.setFont(font)
        self.veh_num_up.setDefault(False)
        self.veh_num_up.setFlat(False)
        self.veh_num_up.setObjectName("veh_num_up")
        self.horizontalLayout.addWidget(self.veh_num_up)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.veh_num_save_btn = QtWidgets.QPushButton(self.widget1)
        self.veh_num_save_btn.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.veh_num_save_btn.setFont(font)
        self.veh_num_save_btn.setDefault(False)
        self.veh_num_save_btn.setFlat(False)
        self.veh_num_save_btn.setObjectName("veh_num_save_btn")
        self.horizontalLayout_5.addWidget(self.veh_num_save_btn)
        self.label_5.raise_()
        self.menuBtn = QtWidgets.QPushButton(self.RDM_page)
        self.menuBtn.setGeometry(QtCore.QRect(20, 6, 40, 40))
        self.menuBtn.setMouseTracking(False)
        self.menuBtn.setStyleSheet("QPushButton {\n"
"    border-image: url(:/menu_graphics/graphics/menu_normal.png);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/menu_graphics/graphics/menu_pressed.png);\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}")
        self.menuBtn.setText("")
        self.menuBtn.setIconSize(QtCore.QSize(50, 50))
        self.menuBtn.setCheckable(False)
        self.menuBtn.setDefault(True)
        self.menuBtn.setFlat(True)
        self.menuBtn.setObjectName("menuBtn")
        self.label_3 = QtWidgets.QLabel(self.RDM_page)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 800, 81))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.RDM_page)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 800, 70))
        self.label_4.setObjectName("label_4")
        self.bgLabel = QtWidgets.QLabel(self.RDM_page)
        self.bgLabel.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.bgLabel.setMouseTracking(True)
        self.bgLabel.setObjectName("bgLabel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.RDM_page)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 70, 361, 351))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget2 = QtWidgets.QWidget(self.groupBox_2)
        self.widget2.setGeometry(QtCore.QRect(20, 32, 321, 301))
        self.widget2.setObjectName("widget2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tm1Label = QtWidgets.QLabel(self.widget2)
        self.tm1Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tm1Label.setObjectName("tm1Label")
        self.gridLayout.addWidget(self.tm1Label, 0, 0, 1, 1)
        self.tm1StatusBox = QtWidgets.QLineEdit(self.widget2)
        self.tm1StatusBox.setMouseTracking(False)
        self.tm1StatusBox.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.tm1StatusBox.setText("")
        self.tm1StatusBox.setAlignment(QtCore.Qt.AlignCenter)
        self.tm1StatusBox.setReadOnly(True)
        self.tm1StatusBox.setObjectName("tm1StatusBox")
        self.gridLayout.addWidget(self.tm1StatusBox, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.tm1_temp_LCD = QtWidgets.QLCDNumber(self.widget2)
        self.tm1_temp_LCD.setMaximumSize(QtCore.QSize(16777215, 40))
        self.tm1_temp_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tm1_temp_LCD.setLineWidth(1)
        self.tm1_temp_LCD.setSmallDecimalPoint(False)
        self.tm1_temp_LCD.setDigitCount(15)
        self.tm1_temp_LCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tm1_temp_LCD.setObjectName("tm1_temp_LCD")
        self.gridLayout.addWidget(self.tm1_temp_LCD, 1, 1, 1, 1)
        self.tm2Label = QtWidgets.QLabel(self.widget2)
        self.tm2Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tm2Label.setObjectName("tm2Label")
        self.gridLayout.addWidget(self.tm2Label, 2, 0, 1, 1)
        self.tm2StatusBox = QtWidgets.QLineEdit(self.widget2)
        self.tm2StatusBox.setMouseTracking(False)
        self.tm2StatusBox.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.tm2StatusBox.setText("")
        self.tm2StatusBox.setAlignment(QtCore.Qt.AlignCenter)
        self.tm2StatusBox.setReadOnly(True)
        self.tm2StatusBox.setObjectName("tm2StatusBox")
        self.gridLayout.addWidget(self.tm2StatusBox, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.tm2_temp_LCD = QtWidgets.QLCDNumber(self.widget2)
        self.tm2_temp_LCD.setMaximumSize(QtCore.QSize(16777215, 40))
        self.tm2_temp_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tm2_temp_LCD.setLineWidth(1)
        self.tm2_temp_LCD.setDigitCount(15)
        self.tm2_temp_LCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tm2_temp_LCD.setObjectName("tm2_temp_LCD")
        self.gridLayout.addWidget(self.tm2_temp_LCD, 3, 1, 1, 1)
        self.epbBtn = QtWidgets.QPushButton(self.RDM_page)
        self.epbBtn.setGeometry(QtCore.QRect(740, 6, 40, 40))
        self.epbBtn.setStyleSheet("QPushButton {\n"
"    border-image: url(:/epb_graphics/graphics/epb_normal.png);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/epb_graphics/graphics/epb_pressed.png);\n"
"}")
        self.epbBtn.setText("")
        self.epbBtn.setIconSize(QtCore.QSize(50, 50))
        self.epbBtn.setFlat(True)
        self.epbBtn.setObjectName("epbBtn")
        self.inverterGroupdBox = QtWidgets.QGroupBox(self.RDM_page)
        self.inverterGroupdBox.setGeometry(QtCore.QRect(37, 170, 351, 71))
        self.inverterGroupdBox.setObjectName("inverterGroupdBox")
        self.widget3 = QtWidgets.QWidget(self.inverterGroupdBox)
        self.widget3.setGeometry(QtCore.QRect(11, 25, 331, 34))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TM1_radio_btn = QtWidgets.QRadioButton(self.widget3)
        self.TM1_radio_btn.setEnabled(True)
        self.TM1_radio_btn.setObjectName("TM1_radio_btn")
        self.horizontalLayout_2.addWidget(self.TM1_radio_btn)
        self.TM2_radio_btn = QtWidgets.QRadioButton(self.widget3)
        self.TM2_radio_btn.setEnabled(True)
        self.TM2_radio_btn.setObjectName("TM2_radio_btn")
        self.horizontalLayout_2.addWidget(self.TM2_radio_btn)
        self.Both_radio_btn = QtWidgets.QRadioButton(self.widget3)
        self.Both_radio_btn.setEnabled(True)
        self.Both_radio_btn.setObjectName("Both_radio_btn")
        self.horizontalLayout_2.addWidget(self.Both_radio_btn)
        self.TorqueGroupdBox = QtWidgets.QGroupBox(self.RDM_page)
        self.TorqueGroupdBox.setGeometry(QtCore.QRect(37, 340, 351, 81))
        self.TorqueGroupdBox.setObjectName("TorqueGroupdBox")
        self.widget4 = QtWidgets.QWidget(self.TorqueGroupdBox)
        self.widget4.setGeometry(QtCore.QRect(15, 23, 321, 47))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.torqueCmdMinus = QtWidgets.QPushButton(self.widget4)
        self.torqueCmdMinus.setMinimumSize(QtCore.QSize(50, 45))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.torqueCmdMinus.setFont(font)
        self.torqueCmdMinus.setStyleSheet("QPushButton {\n"
"    font: 30pt \"MS Shell Dlg 2\";\n"
"}\n"
"")
        self.torqueCmdMinus.setObjectName("torqueCmdMinus")
        self.horizontalLayout_4.addWidget(self.torqueCmdMinus)
        self.torqueCmdBox = QtWidgets.QLineEdit(self.widget4)
        self.torqueCmdBox.setMinimumSize(QtCore.QSize(45, 45))
        self.torqueCmdBox.setText("")
        self.torqueCmdBox.setAlignment(QtCore.Qt.AlignCenter)
        self.torqueCmdBox.setObjectName("torqueCmdBox")
        self.horizontalLayout_4.addWidget(self.torqueCmdBox)
        self.torqueCmdPlus = QtWidgets.QPushButton(self.widget4)
        self.torqueCmdPlus.setMinimumSize(QtCore.QSize(50, 45))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.torqueCmdPlus.setFont(font)
        self.torqueCmdPlus.setStyleSheet("QPushButton {\n"
"    font: 30pt \"MS Shell Dlg 2\";\n"
"}\n"
"")
        self.torqueCmdPlus.setFlat(False)
        self.torqueCmdPlus.setObjectName("torqueCmdPlus")
        self.horizontalLayout_4.addWidget(self.torqueCmdPlus)
        self.groupBox_5 = QtWidgets.QGroupBox(self.RDM_page)
        self.groupBox_5.setGeometry(QtCore.QRect(37, 69, 351, 91))
        self.groupBox_5.setObjectName("groupBox_5")
        self.widget5 = QtWidgets.QWidget(self.groupBox_5)
        self.widget5.setGeometry(QtCore.QRect(11, 30, 331, 44))
        self.widget5.setObjectName("widget5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.startStopBtn = QtWidgets.QPushButton(self.widget5)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startStopBtn.setFont(font)
        self.startStopBtn.setStyleSheet("")
        self.startStopBtn.setObjectName("startStopBtn")
        self.horizontalLayout_6.addWidget(self.startStopBtn)
        self.enableBtn = QtWidgets.QPushButton(self.widget5)
        self.enableBtn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enableBtn.setFont(font)
        self.enableBtn.setStyleSheet("")
        self.enableBtn.setObjectName("enableBtn")
        self.horizontalLayout_6.addWidget(self.enableBtn)
        self.bgLabel.raise_()
        self.groupBox_3.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.groupBox_2.raise_()
        self.epbBtn.raise_()
        self.menuBtn.raise_()
        self.inverterGroupdBox.raise_()
        self.TorqueGroupdBox.raise_()
        self.groupBox_5.raise_()
        self.stackedWidget.addWidget(self.RDM_page)
        self.EPB_page = QtWidgets.QWidget()
        self.EPB_page.setObjectName("EPB_page")
        self.bgLabel_2 = QtWidgets.QLabel(self.EPB_page)
        self.bgLabel_2.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.bgLabel_2.setMouseTracking(True)
        self.bgLabel_2.setObjectName("bgLabel_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.EPB_page)
        self.groupBox_4.setGeometry(QtCore.QRect(70, 149, 671, 311))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 36, 641, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.LtActrStateLabel = QtWidgets.QLabel(self.layoutWidget)
        self.LtActrStateLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LtActrStateLabel.setObjectName("LtActrStateLabel")
        self.gridLayout_3.addWidget(self.LtActrStateLabel, 0, 0, 1, 1)
        self.LtActrStateStatusBox = QtWidgets.QLineEdit(self.layoutWidget)
        self.LtActrStateStatusBox.setMouseTracking(False)
        self.LtActrStateStatusBox.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.LtActrStateStatusBox.setAlignment(QtCore.Qt.AlignCenter)
        self.LtActrStateStatusBox.setReadOnly(True)
        self.LtActrStateStatusBox.setObjectName("LtActrStateStatusBox")
        self.gridLayout_3.addWidget(self.LtActrStateStatusBox, 0, 1, 1, 1)
        self.EpbSwLabel = QtWidgets.QLabel(self.layoutWidget)
        self.EpbSwLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.EpbSwLabel.setObjectName("EpbSwLabel")
        self.gridLayout_3.addWidget(self.EpbSwLabel, 0, 2, 1, 1)
        self.EpbSwStatusBox = QtWidgets.QLineEdit(self.layoutWidget)
        self.EpbSwStatusBox.setMouseTracking(False)
        self.EpbSwStatusBox.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.EpbSwStatusBox.setAlignment(QtCore.Qt.AlignCenter)
        self.EpbSwStatusBox.setReadOnly(True)
        self.EpbSwStatusBox.setObjectName("EpbSwStatusBox")
        self.gridLayout_3.addWidget(self.EpbSwStatusBox, 0, 3, 1, 1)
        self.RtActrStateLabel = QtWidgets.QLabel(self.layoutWidget)
        self.RtActrStateLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.RtActrStateLabel.setObjectName("RtActrStateLabel")
        self.gridLayout_3.addWidget(self.RtActrStateLabel, 1, 0, 1, 1)
        self.RtActrStateStatusBox = QtWidgets.QLineEdit(self.layoutWidget)
        self.RtActrStateStatusBox.setMouseTracking(False)
        self.RtActrStateStatusBox.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.RtActrStateStatusBox.setAlignment(QtCore.Qt.AlignCenter)
        self.RtActrStateStatusBox.setReadOnly(True)
        self.RtActrStateStatusBox.setObjectName("RtActrStateStatusBox")
        self.gridLayout_3.addWidget(self.RtActrStateStatusBox, 1, 1, 1, 1)
        self.EpbFaultLabel = QtWidgets.QLabel(self.layoutWidget)
        self.EpbFaultLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.EpbFaultLabel.setObjectName("EpbFaultLabel")
        self.gridLayout_3.addWidget(self.EpbFaultLabel, 1, 2, 1, 1)
        self.EpbFaultStatusBox = QtWidgets.QLineEdit(self.layoutWidget)
        self.EpbFaultStatusBox.setMouseTracking(False)
        self.EpbFaultStatusBox.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.EpbFaultStatusBox.setAlignment(QtCore.Qt.AlignCenter)
        self.EpbFaultStatusBox.setReadOnly(True)
        self.EpbFaultStatusBox.setObjectName("EpbFaultStatusBox")
        self.gridLayout_3.addWidget(self.EpbFaultStatusBox, 1, 3, 1, 1)
        self.LtActrFaultLabel = QtWidgets.QLabel(self.layoutWidget)
        self.LtActrFaultLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LtActrFaultLabel.setObjectName("LtActrFaultLabel")
        self.gridLayout_3.addWidget(self.LtActrFaultLabel, 2, 0, 1, 1)
        self.LtActrFaultStatusBox = QtWidgets.QLineEdit(self.layoutWidget)
        self.LtActrFaultStatusBox.setMouseTracking(False)
        self.LtActrFaultStatusBox.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.LtActrFaultStatusBox.setAlignment(QtCore.Qt.AlignCenter)
        self.LtActrFaultStatusBox.setReadOnly(True)
        self.LtActrFaultStatusBox.setObjectName("LtActrFaultStatusBox")
        self.gridLayout_3.addWidget(self.LtActrFaultStatusBox, 2, 1, 1, 1)
        self.PGearLabel = QtWidgets.QLabel(self.layoutWidget)
        self.PGearLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PGearLabel.setObjectName("PGearLabel")
        self.gridLayout_3.addWidget(self.PGearLabel, 2, 2, 1, 1)
        self.PGearStatusBox = QtWidgets.QLineEdit(self.layoutWidget)
        self.PGearStatusBox.setMouseTracking(False)
        self.PGearStatusBox.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.PGearStatusBox.setAlignment(QtCore.Qt.AlignCenter)
        self.PGearStatusBox.setReadOnly(True)
        self.PGearStatusBox.setObjectName("PGearStatusBox")
        self.gridLayout_3.addWidget(self.PGearStatusBox, 2, 3, 1, 1)
        self.RtActrFaultLabel = QtWidgets.QLabel(self.layoutWidget)
        self.RtActrFaultLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.RtActrFaultLabel.setObjectName("RtActrFaultLabel")
        self.gridLayout_3.addWidget(self.RtActrFaultLabel, 3, 0, 1, 1)
        self.RtActrFaultStatusBox = QtWidgets.QLineEdit(self.layoutWidget)
        self.RtActrFaultStatusBox.setMouseTracking(False)
        self.RtActrFaultStatusBox.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.RtActrFaultStatusBox.setAlignment(QtCore.Qt.AlignCenter)
        self.RtActrFaultStatusBox.setReadOnly(True)
        self.RtActrFaultStatusBox.setObjectName("RtActrFaultStatusBox")
        self.gridLayout_3.addWidget(self.RtActrFaultStatusBox, 3, 1, 1, 1)
        self.PBrakeLabel = QtWidgets.QLabel(self.layoutWidget)
        self.PBrakeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PBrakeLabel.setObjectName("PBrakeLabel")
        self.gridLayout_3.addWidget(self.PBrakeLabel, 3, 2, 1, 1)
        self.PBrakeStatusBox = QtWidgets.QLineEdit(self.layoutWidget)
        self.PBrakeStatusBox.setMouseTracking(False)
        self.PBrakeStatusBox.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.PBrakeStatusBox.setAlignment(QtCore.Qt.AlignCenter)
        self.PBrakeStatusBox.setReadOnly(True)
        self.PBrakeStatusBox.setObjectName("PBrakeStatusBox")
        self.gridLayout_3.addWidget(self.PBrakeStatusBox, 3, 3, 1, 1)
        self.EPB_startStopBtn = QtWidgets.QPushButton(self.EPB_page)
        self.EPB_startStopBtn.setGeometry(QtCore.QRect(70, 90, 93, 33))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.EPB_startStopBtn.setFont(font)
        self.EPB_startStopBtn.setStyleSheet("")
        self.EPB_startStopBtn.setObjectName("EPB_startStopBtn")
        self.rdmBtn = QtWidgets.QPushButton(self.EPB_page)
        self.rdmBtn.setGeometry(QtCore.QRect(20, 6, 40, 40))
        self.rdmBtn.setMouseTracking(False)
        self.rdmBtn.setStyleSheet("QPushButton {\n"
"    border-image: url(:/rdm_graphics/graphics/rdm_normal.png);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/rdm_graphics/graphics/rdm_pressed.png);\n"
"}")
        self.rdmBtn.setText("")
        self.rdmBtn.setIconSize(QtCore.QSize(50, 50))
        self.rdmBtn.setCheckable(False)
        self.rdmBtn.setDefault(True)
        self.rdmBtn.setFlat(True)
        self.rdmBtn.setObjectName("rdmBtn")
        self.label_8 = QtWidgets.QLabel(self.EPB_page)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 800, 70))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.EPB_page)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 800, 81))
        self.label_9.setObjectName("label_9")
        self.bgLabel_2.raise_()
        self.label_9.raise_()
        self.groupBox_4.raise_()
        self.EPB_startStopBtn.raise_()
        self.label_8.raise_()
        self.rdmBtn.raise_()
        self.stackedWidget.addWidget(self.EPB_page)
        self.stackedWidget.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.Operator_page.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Vehicle in Test"))
        self.label_6.setText(_translate("MainWindow", "PV"))
        self.veh_num_down_2.setText(_translate("MainWindow", "<"))
        self.veh_num_up_2.setText(_translate("MainWindow", ">"))
        self.veh_num_save_btn_2.setText(_translate("MainWindow", "SAVE"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/titlebar/graphics/titlebar.png\"/></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">RDM Bench</span></p></body></html>"))
        self.bgLabel_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/background/graphics/revero_800.png\"/></p></body></html>"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Status"))
        self.tm1Label_2.setText(_translate("MainWindow", "TM1 Status"))
        self.label_11.setText(_translate("MainWindow", "TM1 Temp"))
        self.tm2Label_2.setText(_translate("MainWindow", "TM2 Status"))
        self.label_12.setText(_translate("MainWindow", "TM2 Temp"))
        self.inverterGroupdBox_2.setTitle(_translate("MainWindow", "Inverter Set"))
        self.TM1_radio_btn_2.setText(_translate("MainWindow", "TM1 Only"))
        self.TM2_radio_btn_2.setText(_translate("MainWindow", "TM2 Only"))
        self.Both_radio_btn_2.setText(_translate("MainWindow", "Both"))
        self.TorqueGroupdBox_2.setTitle(_translate("MainWindow", "Torque Control"))
        self.torqueCmdMinus_2.setText(_translate("MainWindow", "-"))
        self.torqueCmdPlus_2.setText(_translate("MainWindow", "+"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Control"))
        self.startStopBtn_2.setText(_translate("MainWindow", "Start"))
        self.enableBtn_2.setText(_translate("MainWindow", "Enable"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Test Profiles:"))
        self.radioButton_2.setText(_translate("MainWindow", "RDM Test #1"))
        self.LED_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/LED/graphics/grey_led.png\"/></p></body></html>"))
        self.bgLabel_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/background/graphics/revero_800.png\"/></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">RDM Bench</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/titlebar/graphics/titlebar.png\"/></p></body></html>"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Test Profiles:"))
        self.radioButton_3.setText(_translate("MainWindow", "RDM Test #1"))
        self.LED_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/LED/graphics/grey_led.png\"/><img src=\":/LED/graphics/green_led.png\"/><img src=\":/LED/graphics/red_led.png\"/></p></body></html>"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Vehicle in Test"))
        self.label_15.setText(_translate("MainWindow", "PV"))
        self.op_veh_num_down.setText(_translate("MainWindow", "<"))
        self.op_veh_num_up.setText(_translate("MainWindow", ">"))
        self.op_veh_num_save_btn.setText(_translate("MainWindow", "SAVE"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Status"))
        self.tm1Label_3.setText(_translate("MainWindow", "TM1 Status"))
        self.label_16.setText(_translate("MainWindow", "TM1 Inv Temp"))
        self.label_18.setText(_translate("MainWindow", "TM1 Motor Temp"))
        self.tm2Label_3.setText(_translate("MainWindow", "TM2 Status"))
        self.label_17.setText(_translate("MainWindow", "TM2 Inv Temp"))
        self.label_19.setText(_translate("MainWindow", "TM2 Motor Temp"))
        self.op_startStopBtn.setText(_translate("MainWindow", "Start"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Vehicle in Test"))
        self.label_5.setText(_translate("MainWindow", "PV"))
        self.veh_num_down.setText(_translate("MainWindow", "<"))
        self.veh_num_up.setText(_translate("MainWindow", ">"))
        self.veh_num_save_btn.setText(_translate("MainWindow", "SAVE"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/titlebar/graphics/titlebar.png\"/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">RDM Bench</span></p></body></html>"))
        self.bgLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/background/graphics/revero_800.png\"/></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Status"))
        self.tm1Label.setText(_translate("MainWindow", "TM1 Status"))
        self.label.setText(_translate("MainWindow", "TM1 Inv Temp"))
        self.tm2Label.setText(_translate("MainWindow", "TM2 Status"))
        self.label_2.setText(_translate("MainWindow", "TM2 Inv Temp"))
        self.inverterGroupdBox.setTitle(_translate("MainWindow", "Inverter Set"))
        self.TM1_radio_btn.setText(_translate("MainWindow", "TM1 Only"))
        self.TM2_radio_btn.setText(_translate("MainWindow", "TM2 Only"))
        self.Both_radio_btn.setText(_translate("MainWindow", "Both"))
        self.TorqueGroupdBox.setTitle(_translate("MainWindow", "Torque Control"))
        self.torqueCmdMinus.setText(_translate("MainWindow", "-"))
        self.torqueCmdPlus.setText(_translate("MainWindow", "+"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Control"))
        self.startStopBtn.setText(_translate("MainWindow", "Start"))
        self.enableBtn.setText(_translate("MainWindow", "Enable"))
        self.bgLabel_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/background/graphics/revero_800.png\"/></p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "EPB Status"))
        self.LtActrStateLabel.setText(_translate("MainWindow", "LT_ACTR_STATE"))
        self.LtActrStateStatusBox.setText(_translate("MainWindow", "releasing"))
        self.EpbSwLabel.setText(_translate("MainWindow", "EPB_SW_STATE"))
        self.EpbSwStatusBox.setText(_translate("MainWindow", "releasing"))
        self.RtActrStateLabel.setText(_translate("MainWindow", "RT_ACTR_STATE"))
        self.RtActrStateStatusBox.setText(_translate("MainWindow", "releasing"))
        self.EpbFaultLabel.setText(_translate("MainWindow", "EPB_FAULT"))
        self.EpbFaultStatusBox.setText(_translate("MainWindow", "releasing"))
        self.LtActrFaultLabel.setText(_translate("MainWindow", "LT_ACTR_FAULT"))
        self.LtActrFaultStatusBox.setText(_translate("MainWindow", "releasing"))
        self.PGearLabel.setText(_translate("MainWindow", "PGEAR"))
        self.PGearStatusBox.setText(_translate("MainWindow", "releasing"))
        self.RtActrFaultLabel.setText(_translate("MainWindow", "RT_ACTR_FAULT"))
        self.RtActrFaultStatusBox.setText(_translate("MainWindow", "releasing"))
        self.PBrakeLabel.setText(_translate("MainWindow", "PBRAKE"))
        self.PBrakeStatusBox.setText(_translate("MainWindow", "releasing"))
        self.EPB_startStopBtn.setText(_translate("MainWindow", "Start"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">EPB Bench</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/titlebar/graphics/titlebar.png\"/></p></body></html>"))

import rdm_graphics_rc
